### ISSUE TITLE
Grafana dashboard example config 

### ISSUE THREAD

**Issue by anhkind** [FokiDoki/WireRest#71]
The example config on [WireRest Grafana dashboard](https://grafana.com/grafana/dashboards/19458-wireguard-wirerest-jvm/) is outdated/incorrect at the moment.  I've changed it to something like this [gist](https://gist.github.com/anhkind/fdc78e36b4da2f23e879c3521e7a858c) and it's now working great. 

```yml
# For Grafana dashboard: https://grafana.com/grafana/dashboards/19458-wireguard-wirerest-jvm/
# put these under `metrics.configs.scrape_configs`
      - job_name: 'wirerest'
        metrics_path: '/actuator/prometheus'
        authorization:
          credentials: YOUR_WIREREST_TOKEN
        static_configs:    
          targets: ['YOUR_WIREREST_IP:8081']
```

Please help update it if necessary. Thanks.
